In [1]:
import torch
data = torch.load("pretrained_weight.pth")
print(data.keys())


odict_keys(['conv1.weight', 'bn1.running_mean', 'bn1.running_var', 'bn1.weight', 'bn1.bias', 'layer1.0.conv1.weight', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.conv2.weight', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.conv3.weight', 'layer1.0.bn3.running_mean', 'layer1.0.bn3.running_var', 'layer1.0.bn3.weight', 'layer1.0.bn3.bias', 'layer1.0.downsample.0.weight', 'layer1.0.downsample.1.running_mean', 'layer1.0.downsample.1.running_var', 'layer1.0.downsample.1.weight', 'layer1.0.downsample.1.bias', 'layer1.1.conv1.weight', 'layer1.1.bn1.running_mean', 'layer1.1.bn1.running_var', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.conv2.weight', 'layer1.1.bn2.running_mean', 'layer1.1.bn2.running_var', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer1.1.conv3.weight', 'layer1.1.bn3.running_mean', 'layer1.1.bn3.running_var', 'layer1.1.bn3.weight', 'la

In [4]:

print(data['conv1.weight'].shape)
print(data['layer1.0.conv1.weight'].shape)

print(data['layer1.1.conv1.weight'].shape)

torch.Size([64, 3, 7, 7])
torch.Size([64, 64, 1, 1])
torch.Size([64, 256, 1, 1])


In [2]:

print(data['bn1.bias'].shape)
print(data['layer1.0.bn3.running_mean'].shape)

torch.Size([64])
torch.Size([256])


In [3]:
print(data['fc.weight'].shape)
print(data['fc.bias'].shape)

torch.Size([1000, 2048])
torch.Size([1000])


In [9]:
import numpy as np

k = np.array(np.ones(shape=(32,64,64)))
k2 = np.ones(shape=(32))  # 예시로 모든 값이 1인 배열을 생성합니다.

result = k - k2[:, np.newaxis, np.newaxis]  # k2 배열을 브로드캐스팅하여 빼기 연산 수행
print(result)


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [6]:
print(data['layer1.0.downsample.0.weight'].tolist())
           

[[[[0.007581142708659172]], [[-0.16594034433364868]], [[0.009154632687568665]], [[0.009196615777909756]], [[0.006325200200080872]], [[0.034098830074071884]], [[-0.0038908468559384346]], [[-0.007323145866394043]], [[-0.0028776272665709257]], [[0.025601806119084358]], [[-0.005788578186184168]], [[-0.02455572411417961]], [[-0.029489124193787575]], [[-2.989814840148597e-09]], [[-0.01562722772359848]], [[0.008747194893658161]], [[-0.0023096995428204536]], [[-0.007192443590611219]], [[-0.023149296641349792]], [[-0.5140810608863831]], [[0.002711355686187744]], [[-0.02159855142235756]], [[0.0077559128403663635]], [[0.009089278988540173]], [[-0.013402203097939491]], [[0.058109622448682785]], [[0.005440404172986746]], [[-0.018584052100777626]], [[0.002691298257559538]], [[0.0948745459318161]], [[0.030214926227927208]], [[-0.013741891831159592]], [[-0.05489147827029228]], [[0.015228875912725925]], [[-0.12605614960193634]], [[-0.052179787307977676]], [[0.024673523381352425]], [[0.01034884992986917

In [8]:
print((data["bn1.running_mean"]))
print((data["bn1.running_var"]))
print((data["bn1.weight"].shape))
print(data["bn1.bias"].shape)

tensor([ 2.4589e-04, -6.6723e-02,  8.1560e-03, -1.1569e-02,  9.1918e-04,
        -3.9417e-03,  6.8244e-05, -1.0278e-04,  6.2920e-05,  1.0156e-02,
        -1.3827e-03,  8.5514e-03, -9.6786e-04, -5.0542e-09, -1.3922e-03,
         9.7684e-04, -4.2287e-03, -4.3058e-04,  8.8580e-04, -5.7929e-02,
         3.4196e-03, -6.9578e-04, -2.2842e-03,  4.3616e-02,  2.6490e-03,
         4.7517e-03, -1.1206e-03, -3.1145e-04,  2.6560e-03,  5.6712e-02,
        -6.8490e-04, -5.3309e-03, -1.4519e-02, -5.2398e-04, -3.5607e-02,
         8.8422e-02,  1.7903e-03,  4.4882e-03,  1.6055e-03, -3.0522e-04,
         2.9796e-03, -1.2307e-03,  7.8966e-03,  5.9528e-03,  9.8027e-03,
        -1.4366e-03,  3.5911e-04, -9.7358e-04, -9.1738e-03,  7.6298e-05,
        -3.3611e-04, -4.8319e-05,  3.6836e-03, -2.1531e-03, -2.1549e-04,
        -8.7561e-07,  3.4184e-02, -3.5004e-03,  1.1910e-02, -1.0551e-03,
         5.2965e-04,  6.0597e-04, -8.4048e-03, -1.6792e-03])
tensor([1.0956e+00, 3.8935e+00, 4.8601e+00, 5.0922e+00, 5.9482e

In [2]:
class tester1:
    def __init__(self):
        self.test1=1

    def access(self):
        print(self['test1'])

test=tester1()
test.access()

TypeError: 'tester1' object is not subscriptable

In [4]:
data['conv1.weight'].shape

torch.Size([64, 3, 7, 7])

In [13]:
import numpy as np

q= np.array([[[1 for _ in range(1)] for _ in range(2048)] for _ in range(64) ])
q.shape

(64, 2048, 1)

In [2]:
import operators as nn 

conv = nn.conv2D()

print(conv([[[[1,2,3],[1,2,3],[1,2,3]]]]))

1 1
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
(1, 1) 1 5
[[[[9, 15, 9], [9, 18, 15], [3, 9, 15]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 

In [9]:
import operators as nn 

conv = nn.fc()
print(conv)
print(conv([[[[1,2,3],[1,2,3],[1,2,3]]]]))

<module 'operators' (namespace) from ['c:\\Users\\gijin100\\CODE\\resnet50\\operators', 'c:\\Users\\gijin100\\CODE\\resnet50\\operators']>


TypeError: 'module' object is not callable

In [1]:
import numpy as np
from operators import batchNorm2D
import operators as nn
k = [[[ [ 0 for _ in range(3)] for _ in range(3)] for _ in range(7)]  for _ in range(64) ]
nk= np.array(k)
print(nk.shape)

norm2D = nn.batchNorm2D(num_features=64)

print(norm2D(k))


(64, 7, 3, 3)
[[[[0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833]], [[0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833]], [[0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833]], [[0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833]], [[0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833], [0.1265003088864833, 0.1265003088864833, 0.1265003088864833]], [[0.1265003088864833, 0.1265003088864833, 0.

In [5]:
from operators import relu
import operators as nn
Relu = relu
Relu = nn.relu()
normK = norm2D(k)
normK[0][0][0][0] = -1
print(normK[0][0])
reluNorm2D = relu()

print(reluNorm2D(normK))


[[-1, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924]]
[[[[0, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924]], [[0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924]], [[0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924]], [[0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924], [0.015000280805893924, 0.015000280805893924, 0.015000280805893924]], [[0.01

In [2]:
from operators import avgpool
import numpy as np
q= np.array([[[[1.5 for _ in range(3)] for _ in range(3)] for _ in range(2048)] for _ in range(64) ])

pool2D = avgpool()
qq= pool2D(q)
print(len(qq),len(qq[0]),qq[0][0])

64 2048 1.5


In [1]:
from operators import avgpool2
import numpy as np
q= np.array([[[[1.5 for _ in range(3)] for _ in range(3)] for _ in range(2048)] for _ in range(64) ])
pool2D = avgpool2()
qq= pool2D(q)
print(len(qq),len(qq[0]),qq[0][0])

64 2048 1.5


In [1]:
import torch
import torch.nn as nn
import operators as op_nn
import numpy as np
m = nn.Conv2d(3, 64, 3, stride=1,padding=1)
m2 = op_nn.conv2(3,64,(3,3),stride=(1,1),padding=1)
input = torch.randn(1, 3, 64, 64)
input2 = input.tolist()
output = m(input)
output2 = np.array(m2(input2))


In [2]:
print(output.shape)
print(output2.shape)


torch.Size([1, 64, 224, 224])
(1, 64, 224, 224)


In [3]:
print(input[0][0])
print(output2[0][0])
print(output2[0][0][1][1])
#filter에 대해 검증 끝 conv 값 제대로 구함


tensor([[-1.1319,  0.9251,  0.5418,  ..., -1.0345,  0.6502,  0.1745],
        [ 0.0644, -0.5230, -0.6358,  ...,  0.0091,  0.2091, -0.8432],
        [ 0.4057,  0.6711,  0.4283,  ..., -0.2240,  0.2282, -1.0785],
        ...,
        [-0.6650,  1.0004,  0.0030,  ..., -1.3605, -0.6802,  1.0421],
        [-0.7885,  1.3856, -0.5865,  ..., -0.4129,  0.8598,  1.6179],
        [ 0.1107,  0.0643, -0.2934,  ..., -0.8028,  0.1988, -1.0669]])
[[-0.66546448 -0.75945039  0.64206745 ...  0.71094768 -0.83473824
   0.1906237 ]
 [ 0.41130181  0.74562882  3.00921433 ...  1.23593951 -1.90908268
  -0.65974131]
 [ 2.15067597  0.38846438  0.23528033 ...  4.17796067 -1.62720522
  -0.99977767]
 ...
 [ 0.72844727 -1.05977242 -1.66447956 ... -1.4062373   0.10878894
   1.14317271]
 [ 1.10739274  0.23045919  1.26370396 ... -0.64299013 -0.60474773
   1.97141074]
 [ 0.77204318 -0.10788598 -0.57839731 ...  1.19108436  0.39393257
   1.60958664]]
0.7456288188695908


In [1]:
import torch.nn as nn
import operators as op_nn
import torch

relu1 = nn.ReLU()
relu2= op_nn.relu()
input = torch.randn(1, 3, 224, 224)
input2 = input.tolist()

In [2]:
print(relu2.Relu(input2))

[[[[0.21616871654987335, 0, 0.5761092305183411, 2.057945966720581, 1.0402064323425293, 0, 0.4884124994277954, 0.9327017068862915, 0, 0, 0.0304097980260849, 1.3493056297302246, 0, 0.7953954935073853, 0.885250449180603, 1.286956548690796, 1.3901219367980957, 0, 0, 0, 1.0346436500549316, 0, 0.518342912197113, 1.0054194927215576, 0.7327365875244141, 0.47761857509613037, 0.9631787538528442, 0.6202945113182068, 0.7672330141067505, 1.0502922534942627, 0.5062168836593628, 1.6539496183395386, 0.5087782144546509, 1.7708584070205688, 0.18329930305480957, 0.4288281500339508, 0, 0.5020565390586853, 0, 1.2716161012649536, 0, 3.2210237979888916, 0, 1.3081401586532593, 1.9298068284988403, 1.0587157011032104, 0, 0, 1.1227436065673828, 0.6870272755622864, 0.4661729633808136, 0, 0, 0, 1.3378064632415771, 0.6424819231033325, 0, 0, 0.5132213234901428, 0, 0, 0.5996385216712952, 0, 0, 0, 0.27226629853248596, 0.20735929906368256, 0, 0.9378733038902283, 0, 0, 0, 0, 0.6942520141601562, 0, 0, 0, 0, 0, 1.19272446

In [1]:
import torch
import torch.nn as nn
import operators as op_nn
import numpy as np
m = nn.MaxPool2d(3,stride=2,padding=1)
m2 = op_nn.maxpool((3,3),stride=(2,2),padding=1)
input = torch.randn(1, 3, 64, 64)
input2 = input.tolist()

In [2]:
print(m(input)[0][0].shape)
print(m2(input2)[0][0])

torch.Size([32, 32])


IndexError: list index out of range

In [1]:
import resnet50

resnet = resnet50.resnet50()

resnet.load_state_dict()

this is resnet50
load state dict


KeyError: 'layer1.3.conv1.weight'

In [6]:
import copy

a= [[1,2,],[3,4]]
c =[[1,2,],[3,4]]
b=copy.deepcopy(a)

a[0][0]=5
print(b)
print(a+c)

[[1, 2], [3, 4]]
[[5, 2], [3, 4], [1, 2], [3, 4]]


In [1]:
a= [[1,2,3]]
b= a
c= a

c[0][2]=5
print(b)

[[1, 2, 5]]
